### ISSUE TITLE
add windows to continuous integration

### ISSUE THREAD

**Issue by webern** [awslabs/tough#349]
Add Windows to the continuous integration build.

Needs these:
- [x] #343 
- [x] #347
- [ ] #348 (maybe)

**Comment by Cytro54** [comment]
Uh, I wrote a patch to the GitHub action, it can be used as a base to add windows to CI.
Putting it here in hope that it helps someone.

```yml 
name: Rust
on:
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: rustup update stable
    - run: make ci
  build_windows:
    runs-on: windows-latest
    steps:
    - name: Configure Git
      run: git config --global core.autocrlf input
    - uses: actions/checkout@v1
    - name: Check for rust updates
      run: rustup update stable
    - name: Set up Cygwin
      uses: egor-tensin/setup-cygwin@v3
      with:
        install-dir: C:\tools\cygwin
        platform: x64
        packages: make 
    - name: Run 'make ci' under Cygwin/x64
      run: C:\tools\cygwin\bin\bash.exe -l -c cd %GITHUB_WORKSPACE% && make ci
```
Available also here : https://gist.github.com/Cytro54/4dabbf5160bf47fb464781e424e2b0f0
